### ISSUE TITLE
Pretrained model of demo test

### ISSUE THREAD

**Issue by SongMingtao-NUDT** [weitong8591/differentiable_ransac#14]
Hello, thank you for your amazing work.
I notice that the demo test use "pretrained_models/saved_model_5PC_l_epi/model.net" as its model, then I output the dict_keys of model.net. But I found that there are only key_name of ds_0, no key_name about ransac_layer. 
[model_net_keys.txt](https://github.com/user-attachments/files/17816996/model_net_keys.txt)
![DeepRansac_CLNet](https://github.com/user-attachments/assets/c3c3367f-a934-49b0-a979-736793c45f71)
 I don't understand why there is no key_name of ransac_layer, could you please explain it to me?

**Comment by weitong8591** [comment]
Hi, thanks for your interest. It is a differentiable function used to incoporate robust fitting models to the training objectives. The training weights are the ones in the inlier prediction network, which are used in RANSAC sampling process in 'ransac_layer'.
