### ISSUE TITLE
About Local Optimization

### ISSUE THREAD

**Issue by antabangun** [weitong8591/differentiable_ransac#3]
Hello, thanks for your exciting work!
In the Arxiv paper, you mentioned applying RANSAC-based local optimization to improve the accuracy.
I see that the variable `lo` in the RANSAC class has a default value of 0, and I don't see this value being modified anywhere in the code. So I was wondering whether you're using local optimization in your test inference, and if you do, how much does it improve the performance?

**Comment by weitong8591** [comment]
Hi! Thanks for your question, the Python version of RANSAC is mainly used for training, without any optimiztaion. While the testing is worked on C++ implementation of MAGSAC, which is supposed to be the one combined with local optimiztaion, as in the paper. Thanks for the comments, I will add another changable option to `lo` to make Python testing can work with local optimiztaion.

**Comment by antabangun** [comment]
Thanks for your answer!
