### ISSUE TITLE
Data link is broken

### ISSUE THREAD

**Issue by jytime** [weitong8591/differentiable_ransac#4]
Hi Tong,

Thanks for the great work. I am trying to run the test script while the dataset link (https://cmp.felk.cvut.cz/~weitong/diff_ransac_data.zip) seems to be broken. I guess it should be updated to something like https://cmp.felk.cvut.cz/~weitong/diff_ransac_data/data/.

Best,
Jianyuan

**Comment by jytime** [comment]
I download it by a simple script, which may be beneficial to share here.
```
#!/bin/bash

URL="https://cmp.felk.cvut.cz/~weitong/diff_ransac_data/"
TARGET_DIR="YOUR/PATH"

# Ensure wget is installed
if ! command -v wget &> /dev/null; then
    echo "Error: wget is not installed."
    exit 1
fi

# Create target directory if it doesn't exist
mkdir -p "$TARGET_DIR"

# Use wget to download the data
wget \
    --recursive \
    --no-clobber \
    --no-parent \
    --adjust-extension \
    --cut-dirs=2 \
    --no-check-certificate \
    --directory-prefix="$TARGET_DIR" \
    "$URL"

echo "Download complete."
```

**Comment by weitong8591** [comment]
Hi! Thanks for sharing the script. I update the correct link for downloading '*.zip' as well.
