### ISSUE TITLE
Question about datas for training

### ISSUE THREAD

**Issue by shenyehui** [weitong8591/differentiable_ransac#7]
Dear author,

Hello. Following your advice, I used the methods suggested in ngransac to generate some pairs.npy for training. However, the pairs.npy generated by this method differs in some aspects and cannot be used to train differentiate_ransac. Therefore, I plan to use the methods in ars_magsac to generate data for training. Could you please guide me on how to generate the series of h5 files required by ars_magsac? Alternatively, how can I modify the data generation method in ngransac to produce data suitable for training differentiate_ransac?

**Comment by weitong8591** [comment]
The 'npy' files generated from [here ](https://github.com/weitong8591/ars_magsac/blob/main/prepare_data/prepare_data_st.py) should work, which differs from NG-RANSAC by scale and orientation info. Feel free to adjust the data loader/network input dim for your own data. 

'.h5' files are ground truth E, F, K, etc for PhotoTourism downloaded from[ RANSAC tutorial data](https://github.com/ducha-aiki/ransac-tutorial-2020-data). If you are working on other datasets, try to replace reading ground truths from '.h5' files by your own. 

I guess you want to build your own dataset, What are the dataset and feature detection, matching methods you use?

**Comment by shenyehui** [comment]
> The 'npy' files generated from [here ](https://github.com/weitong8591/ars_magsac/blob/main/prepare_data/prepare_data_st.py) should work, which differs from NG-RANSAC by scale and orientation info. Feel free to adjust the data loader/network input dim for your own data.
> 
> '.h5' files are ground truth E, F, K, etc for PhotoTourism downloaded from[ RANSAC tutorial data](https://github.com/ducha-aiki/ransac-tutorial-2020-data). If you are working on other datasets, try to replace reading ground truths from '.h5' files by your own.
> 
> I guess you want to build your own dataset, What are the dataset and feature detection, matching methods you use?

Dear author,

Hello. I am using the KingsCollege scene from the Cambridge dataset for my research. The feature detection and matching methods align with your application 1. I plan to retrain on this dataset to validate the effectiveness of the proposed methods. Therefore, I am currently exploring how to generate the npy files for training.

Best regards.

**Comment by shenyehui** [comment]
I plan to use the method you recommended, args_magsac, to generate npy files for training. However, to use this method, I need to first generate these h5 files. Could you please provide guidance on how to generate them based on my data? My dataset consists of approximately 4500 images along with their poses and intrinsic parameters.


matches = load_h5(f'{DIR}/{seq}/matches.h5')
F_gt = load_h5(f'{DIR}/{seq}/Fgt.h5')
E_gt = load_h5(f'{DIR}/{seq}/Egt.h5')
matches_scores = load_h5(f'{DIR}/{seq}/match_conf.h5')
K1_K2 = load_h5(f'{DIR}/{seq}/K1_K2.h5')
R = load_h5(f'{DIR}/{seq}/R.h5')
T = load_h5(f'{DIR}/{seq}/T.h5')
