### ISSUE TITLE
Question of inputs of ransac layer

### ISSUE THREAD

**Issue by lao-ling-jie** [weitong8591/differentiable_ransac#8]
Thank you for your amazing work. I am new to this field and would like to ask what the k1 and k2 in the ransac layer input represent?
![image](https://github.com/weitong8591/differentiable_ransac/assets/50287419/47aafc2a-e931-46f8-ac8e-262b464beedc)

**Comment by weitong8591** [comment]
Hi, these are calibration matrices of two images.

**Comment by Shiyao-Huang** [comment]
> Hi, these are calibration matrices of two images.
How can I use this method if we don't have any information about K1\K2?

**Comment by weitong8591** [comment]
Hi, sure, input identity matrices for K1, K2 should work. I will give default input for them soon.

**Comment by Shiyao-Huang** [comment]
Thank you for your amazing work! Currently I found that your implementation only has 7-point and 8-point methods for the estimation of the essential matrix, and lacks an estimator for the Homography Matrix， May I ask how to proceed if I want to perform estimation of the Homography Matrix?

**Comment by weitong8591** [comment]
> Thank you for your amazing work! Currently I found that your implementation only has 7-point and 8-point methods for the estimation of the essential matrix, and lacks an estimator for the Homography Matrix， May I ask how to proceed if I want to perform estimation of the Homography Matrix?

Hi! If you want to train/test homography estimation or look for the 4PC solver, I recommand checking the benchmark paper (A Large Scale Homography Benchmark) and use the solver from Kornia directly. https://github.com/danini/homography-benchmark/blob/main/test_kornia.py#L18
