### ISSUE TITLE
findFundamentalMatrix function of pymagsac is incompatible with the code

### ISSUE THREAD

**Issue by cmh1027** [weitong8591/differentiable_ransac#9]
I haven't changed any code in the repo and test_magsac.py gives this error.

```
TypeError: findFundamentalMatrix(): incompatible function arguments. The following argument types are supported:
    1. (correspondences: numpy.ndarray[numpy.float64], w1: float, h1: float, w2: float, h2: float, probabilities: numpy.ndarray[numpy.float64], sampler: int = 4, use_magsac_plus_plus: bool = True, sigma_th: float = 1.0, conf: float = 0.99, min_iters: int = 50, max_iters: int = 1000, partition_num: int = 5) -> tuple

Invoked with: array([[443.9876 , 239.61026],
       [443.9876 , 239.61026],
       [443.9876 , 239.61026],
       ...,
       [328.67685, 423.61395],
       [328.67685, 423.61395],
       [328.67685, 423.61395]], dtype=float32), array([[423.3007 , 328.98468],
       [423.3007 , 328.98468],
       [423.3007 , 328.98468],
       ...,
       [502.42374, 161.1907 ],
       [502.42374, 161.1907 ],
       [502.42374, 161.1907 ]], dtype=float32), 575.0, 1077.0, 694.0, 1067.0; kwargs: probabilities=array([-2.132277e-03, -2.132277e-03, -2.132277e-03, ..., -2.458080e+01,
       -2.458080e+01, -2.458080e+01], dtype=float32), use_magsac_plus_plus=True, sigma_th=2.0, sampler_id=1, save_samples=True
```

pymagsac version is 0.3.dev0

**Comment by cmh1027** [comment]
It seems that installed should be the **ngmagsac-test branch** of magsac repo. README needs renewal.

**Comment by weitong8591** [comment]
> It seems that installed should be the **ngmagsac-test branch** of magsac repo. README needs renewal.

You can also install it from my forked repo, as I wrote in readme.

**Comment by cmh1027** [comment]
@weitong8591 Could you change the linked url in installation section? It directs to the original repo, not the forked one.

**Comment by ABCDZLG** [comment]
> I haven't changed any code in the repo and test_magsac.py gives this error.
> 
> ```
> TypeError: findFundamentalMatrix(): incompatible function arguments. The following argument types are supported:
>     1. (correspondences: numpy.ndarray[numpy.float64], w1: float, h1: float, w2: float, h2: float, probabilities: numpy.ndarray[numpy.float64], sampler: int = 4, use_magsac_plus_plus: bool = True, sigma_th: float = 1.0, conf: float = 0.99, min_iters: int = 50, max_iters: int = 1000, partition_num: int = 5) -> tuple
> 
> Invoked with: array([[443.9876 , 239.61026],
>        [443.9876 , 239.61026],
>        [443.9876 , 239.61026],
>        ...,
>        [328.67685, 423.61395],
>        [328.67685, 423.61395],
>        [328.67685, 423.61395]], dtype=float32), array([[423.3007 , 328.98468],
>        [423.3007 , 328.98468],
>        [423.3007 , 328.98468],
>        ...,
>        [502.42374, 161.1907 ],
>        [502.42374, 161.1907 ],
>        [502.42374, 161.1907 ]], dtype=float32), 575.0, 1077.0, 694.0, 1067.0; kwargs: probabilities=array([-2.132277e-03, -2.132277e-03, -2.132277e-03, ..., -2.458080e+01,
>        -2.458080e+01, -2.458080e+01], dtype=float32), use_magsac_plus_plus=True, sigma_th=2.0, sampler_id=1, save_samples=True
> ```
> 
> pymagsac version is 0.3.dev0

Excuse me, have you solved this problem? If solved, can you tell me the detailed steps? Thank you very much.
